### ISSUE TITLE
Project Tab Manager stopped working on one of my computers

### ISSUE THREAD

**Issue by wpwoodjr** [agektmr/ProjectTabManager#44]
Project Tab Manager stopped working on one of my computers.  I'm not getting bookmarked projects or sessions:
![image](https://cloud.githubusercontent.com/assets/6633152/6110255/7d1575f4-b04e-11e4-96e8-7ef6fdad9525.png)

Not sure what to do!!

**Comment by agektmr** [comment]
I didn't send any updates. Can you do following?

- open chrome://extensions/ in one of chrome tabs
- find Project Tab Manager extension and click "background page" link
- what you see is "DevTools". click on "Console" tab on top of it.
- If you see any messages, please copy and paste them here.

If you don't see any messages, continue with following

- click on Project Tab Manager button
- right click on anywhere in PTM
- click on "Inspect Element"
- what you see is "DevTools". click on "Console" tab on top of it.
- If you see any messages, please copy and paste them here.

Thanks for your continuous contribution to this extension!

**Comment by WPWoodJr** [comment]
Here you go!  :-)

Error in response to windows.getCurrent: TypeError: Cannot read property 'id' of undefined
    at Object.<anonymous> (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:731:37)
    at Object.SessionManager (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:729:20)
    at chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1956:22
    at chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1341:43
    at Object.<anonymous> (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1466:45)
    at Object.callback (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1319:11)
extensions::sendRequest:82 Unchecked runtime.lastError while running windows.getCurrent: No current window
    at Object.SessionManager (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:729:20)
    at chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1956:22
    at chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1341:43
    at Object.<anonymous> (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1466:45)
    at Object.callback (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1319:11)
extensions::uncaught_exception_handler:8 Error in response to windows.getAll: TypeError: Cannot read property 'title' of null
    at new FieldEntity (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1507:51)
    at Object.ProjectEntity.load (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1644:26)
    at Object.ProjectEntity (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1531:10)
    at Object.ProjectManager.update (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1852:19)
    at chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1958:22
    at Object.<anonymous> (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1193:46)
    at Object.<anonymous> (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1176:24)
    at Object.<anonymous> (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:437:11)
10extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'title' of null
    at new FieldEntity (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1507:51)
    at Object.ProjectEntity.load (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1644:26)
    at Object.ProjectEntity (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1531:10)
    at Object.ProjectManager.update (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1852:19)
    at chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1970:41extensions::uncaught_exception_handler:8 handler

**Comment by agektmr** [comment]
Odd. The cause seems yours isn't receiving an expected windowId which works in other places.
Can you think of any reasons? What is different from other in that particular environment?

**Comment by jerrytron** [comment]
Same problem with me. Just stopped working without warning:

Error in response to windows.getAll: TypeError: Cannot read property 'title' of null
    at new FieldEntity (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1507:51)
    at Object.ProjectEntity.load (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1644:26)
    at Object.ProjectEntity (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1531:10)
    at Object.ProjectManager.update (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1852:19)
    at chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1958:22
    at Object.<anonymous> (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1193:46)
    at Object.<anonymous> (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1176:24)
    at Object.<anonymous> (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:437:11)handler @ extensions::uncaught_exception_handler:8
8extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'title' of null
    at new FieldEntity (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1507:51)
    at Object.ProjectEntity.load (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1644:26)
    at Object.ProjectEntity (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1531:10)
    at Object.ProjectManager.update (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1852:19)
    at chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1970:41handler @ extensions::uncaught_exception_handler:8
2extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'title' of null
    at new FieldEntity (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1507:51)
    at Object.ProjectEntity.load (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1644:26)
    at Object.ProjectEntity (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1531:10)
    at Object.ProjectManager.update (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1852:19)
    at chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1970:41handler @ extensions::uncaught_exception_handler:8exports.handle @ extensions::uncaught_exception_handler:100EventImpl.dispatch_ @ extensions::event_bindings:384EventImpl.dispatch @ extensions::event_bindings:401target.(anonymous function) @ extensions::SafeBuiltins:19publicClass.(anonymous function) @ extensions::utils:94messageListener @ extensions::messaging:188target.(anonymous function) @ extensions::SafeBuiltins:19EventImpl.dispatchToListener @ extensions::event_bindings:395target.(anonymous function) @ extensions::SafeBuiltins:19publicClass.(anonymous function) @ extensions::utils:94EventImpl.dispatch_ @ extensions::event_bindings:379EventImpl.dispatch @ extensions::event_bindings:401target.(anonymous function) @ extensions::SafeBuiltins:19publicClass.(anonymous function) @ extensions::utils:94dispatchOnMessage @ extensions::messaging:316

**Comment by jerrytron** [comment]
My Chrome version (though the plugin is still working on my other user in the same browser)

Version 43.0.2342.2 dev (64-bit)

**Comment by agektmr** [comment]
Thanks @jerrytron for the report. I will have a look into this. This might be caused by Chrome itself rather than the extension.

**Comment by agektmr** [comment]
@jerrytron @WPWoodJr Do you still see the issue? I would imagine have already stopped using this exention since it's been 1+ year... Sorry about that.

**Comment by WPWoodJr** [comment]
I did stop using it, but may try it again now.  Thanks for all your work on this!!  :+1:

**Comment by agektmr** [comment]
@WPWoodJr hope issues are sorted for you. Please let me know if you have any troubles.
