### ISSUE TITLE
Empty tab title breaks extension

### ISSUE THREAD

**Issue by makern** [agektmr/ProjectTabManager#48]
One of my tabs has an empty string as title which prevents the extension's popup from populating with the following error:

```
Error in event handler for runtime.onMessage: TypeError: Cannot read property 'title' of null
    at new FieldEntity (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1507:51)
    at Object.ProjectEntity.load (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1644:26)
    at Object.ProjectEntity (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1531:10)
    at Object.ProjectManager.update (chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1852:19)
    at chrome-extension://iapdnheekciiecjijobcglkcgeckpoia/js/background.js:1970:41handler @
```

The line causing the issue is:

```
this.title = tab && tab.title || bookmark.title;
```

tab.title is "" here and bookmark is null. A reasonable fix would perhaps be

```
this.title = tab && (tab.title || tab.url) || bookmark && (bookmark.title || bookmark.url);
```

**Comment by makern** [comment]
Upon closer inspection this is actually not a currently open tab but one saved in `chrome.storage.local`.

**Comment by agektmr** [comment]
Sorry for belated response and thanks for your feedback. This issue will be fixed in the next version. See `polymer` branch for details.
